// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYtTNctxFloWz6_RKpnaBXf3Y3hSIN78M',
    appId: '1:902932250649:web:00441062837f5ec53fea88',
    messagingSenderId: '902932250649',
    projectId: 'chati-app-8b368',
    authDomain: 'chati-app-8b368.firebaseapp.com',
    storageBucket: 'chati-app-8b368.appspot.com',
    measurementId: 'G-4MHZGCB38S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5IbMhJP085q6DK1yDAST1P3pQWuqqTrM',
    appId: '1:902932250649:android:b83f1be361a8af953fea88',
    messagingSenderId: '902932250649',
    projectId: 'chati-app-8b368',
    storageBucket: 'chati-app-8b368.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrKLk3_SAkb_lteA3SKZ4ouB5eOefSHXk',
    appId: '1:902932250649:ios:a9ea318cac63069e3fea88',
    messagingSenderId: '902932250649',
    projectId: 'chati-app-8b368',
    storageBucket: 'chati-app-8b368.appspot.com',
    iosBundleId: 'com.example.chatiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrKLk3_SAkb_lteA3SKZ4ouB5eOefSHXk',
    appId: '1:902932250649:ios:b593e7a9c48db1873fea88',
    messagingSenderId: '902932250649',
    projectId: 'chati-app-8b368',
    storageBucket: 'chati-app-8b368.appspot.com',
    iosBundleId: 'com.example.chatiApp.RunnerTests',
  );
}
